### ISSUE TITLE
[REQUEST] Edit Text

### ISSUE THREAD

**Issue by God-damnit-all** [JackyDing/EnvMan#3]
EnvMan is a wonderful replacement for `sysdm.cpl,EditEnvironmentVariables`, but it is missing one thing. `sysdm.cpl,EditEnvironmentVariables` has an 'Edit Text' option that will pull up a plain text view of the variable, like so:

![image](https://user-images.githubusercontent.com/53661808/69171895-6bfe9100-0ac2-11ea-8c9a-650e5f6f61f8.png)

I would like it if EnvMan had the same option, but with a much larger text display for long PATH variables.

**Comment by JackyDing** [comment]
Add text edit mode

**Comment by God-damnit-all** [comment]
Thanks!
