### ISSUE TITLE
[CRITICAL] EnvMan cannot save more than 1024 characters in a variable

### ISSUE THREAD

**Issue by God-damnit-all** [JackyDing/EnvMan#4]
I just noticed this. While exporting works fine, trying to save a PATH that has a lot added to it that's over this 1024 character count will be cut off. Thankfully I had a backup but this sadly makes the program unusable.

**Comment by JackyDing** [comment]
Which OS version do you work on? It seems fine on lastest Windows 10.

**Comment by God-damnit-all** [comment]
I am on the latest Windows 10 as well. Save a very long variable in EnvMan, close EnvMan, and then run `rundll32 sysdm.cpl,EditEnvironmentVariables` and check that same variable.

**Comment by God-damnit-all** [comment]
It seems recompiling with the new VS2019 sln provided has fixed the issue!

**Comment by God-damnit-all** [comment]
@JackyDing I've figured out why this problem occurs and why recompiling fixed it.

When you added app.manifest, it set the requestedExecutionLevel to requireAdministrator, meaning it requires admin to launch. This was significant because it seems the bug only occurs when it it has to request administrator (when launched as a non-administrator) in order to save a system variable. 

Or, to put it succinctly, as long as it is ran as administrator, the problem does not occur.

I'm not sure if requiring administrator was an intended change. If so, feel free to re-close this issue.

**Comment by JackyDing** [comment]
Yes. There are two code pathes when save the varaible, one for non-elevated mode, which by executing SETX.exe command line application, and the other, Administrator mode,  by manipulating System Registry. These two approaches have different restriction on max length of value. As of in SETX, the max-length acceptable is 1023.

**Comment by JackyDing** [comment]
I seems useful if this program can be run as non-administrator, so I will remove the manifest file. Thank you for your suggestion. However, the max-length restriction will still be there if we don't change the implementation.

**Comment by God-damnit-all** [comment]
Why not do it through powershell instead? `[Environment]::SetEnvironmentVariable('envVar','envValue','Machine')`

**Comment by God-damnit-all** [comment]
See #8
