### ISSUE TITLE
[BUG] As Grid can't handle As Text variables that end in a semi-colon

### ISSUE THREAD

**Issue by God-damnit-all** [JackyDing/EnvMan#6]
Similar to #5, only with the new As Text feature. If the variable you're working with has a semi-colon at the end of it and you switch to As Text and then back to As Grid **OR** if you put a semi-colon at the end of a variable in As Text, you will get that same invalid blank entry that you can't delete.

Interestingly, As Text will omit the ending semi-colon when you switch to it, but that doesn't seem to matter when you switch back to As Grid.

**Comment by JackyDing** [comment]
@ImportTaste ,blank cells are intented to be treated as legal entries in my last commit, so the variable ends with semi-colon will be editable both in grid mode and text mode. Your problem does not happen in my side, it's a bit strange.

**Comment by God-damnit-all** [comment]
I'm not sure why you weren't able to replicate, but the good news is that https://github.com/JackyDing/EnvMan/commit/26c12b67d12facc6100442440ba193b02993b26b fixes the issue.
